#!/usr/bin/env bash

cd /tmp

echo
echo "## Download the latest perlbrew"
curl -O https://github.com/gugod/App-perlbrew/raw/master/perlbrew >/dev/null 2>&1

echo "## Download the packed patchperl"
curl -O https://gist.github.com/raw/962406/67851841951266c22559f2e9c36b508a0ae30be1/patchperl >/dev/null 2>&1

echo
echo "## Installing perlbrew"
chmod +x perlbrew
./perlbrew install

echo "## Installing patchperl"
if [ "X${PERLBREW_ROOT}" == "X" ]; then
    PERLBREW_ROOT="${HOME}/perl5/perlbrew"
fi
chmod +x patchperl
cp patchperl "${PERLBREW_ROOT}/bin"

echo
echo "## Done."
rm ./perlbrew
rm ./patchperl
