#!/usr/bin/env bash

cd /tmp

echo
echo "## Download the latest perlbrew"
curl -Lo perlbrew https://raw.github.com/gugod/App-perlbrew/master/perlbrew >/dev/null 2>&1

echo "## Download the packed patchperl"
curl -Lo patchperl https://raw.github.com/gist/962406/5aa30dd2ec33cd9cea42ed2125154dcc1406edbc >/dev/null 2>&1

echo
echo "## Installing perlbrew"
chmod +x perlbrew
./perlbrew install

echo "## Installing patchperl"
if [ "X${PERLBREW_ROOT}" == "X" ]; then
    PERLBREW_ROOT="${HOME}/perl5/perlbrew"
fi
mkdir -p "$PERLBREW_ROOT"

chmod +x patchperl
cp patchperl "${PERLBREW_ROOT}/bin"

echo
echo "## Done."
rm ./perlbrew
rm ./patchperl
