# Here's some random notes about perlbrew that I take when I was thinking (or not.)

* shell integration

bashrc / cshrc should check if ~/.perlbrew/init before sourcing it.
If ~/.perlbrew/init is missing, it is the same as perlbrew is not in effect.

* info command

    $ perlbrew info
    
    perlbrew version 0.30
        with bash integration
    
    PERLBREW_ROOT=...
    PERLBREW_HOME=...

    Disk Usage: 230MB

    $ perlbrew info perl-5.14.2

    perl version 5.14.2, installed at $PERLBREW_ROOT/perls/perl-5.14.2

    #Show the platform section of `perl -V`
    [x] Show the value of `Compiled at` from `perl -V`

* When it is installed with cpan
  - `which perlbrew` is, most likely, not equal to "$PERLBREW_ROOT/bin/perlbrew"
  - Directories and files under $PERLBREW_ROOT/* might be absent
  * as a result, user need to go through a initialization process. to get $PERLBREW_ROOT ready
    - why ? can it be built on-the go ?
    - etc/bashrc and etc/cshrc makes it harder
    - When people run `perlbrew` for the very first time, perform `init`
    - When people run `perlbrew install 5.14.2` the very first time, perform `init`

* When it is installed with the perlbrew installer

* Black box testing

  Suppose: A fresh bash user.
  scripts to test the stand-alone `perlbrew` behaviour
  scripts to test the cpan-installed `perlbrew` behaviour
