name: coverage

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: 'ubuntu-latest'
    name: Coverage
    container:
      image: perl:stable
    steps:
      - uses: actions/checkout@v2
      - run: cpanm --quiet --notest --installdeps .
      - run: cpanm --quiet --notest App::Yath Devel::Cover Devel::Cover::Report::Coveralls
      - run: PERL5OPT=-MDevel::Cover yath test --qvf t/
      - run: cover -report coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
