name: E2E

on:
  workflow_dispatch:
  pull_request:
    paths:
      - perlbrew
  push:
    paths:
      - perlbrew

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install zsh
      - run: zsh ./test-e2e/run.zsh

  macos:
    strategy:
      matrix:
        os: ["macos-latest", "macos-13"]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: shogo82148/actions-setup-perl@v1.31.3
        with:
          perl-version: "5.40"
      - uses: actions/checkout@v4
      - run: /bin/zsh ./test-e2e/run.zsh
