name: Lint

on: pull_request

jobs:
  perlcritic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gugod/actions-perlcritic@fun
        with:
          options: --quiet -p .perlcriticrc
          paths: lib script t dev-bin
