name: Lint

on: pull_request

jobs:
  perlcritic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gugod/action-perlcritic@fun
        with:
          perlcritic_args: -p .perlcriticrc lib t scripts dev-bin
